# docker-compose.yml

version: "3.8"
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=RecipePassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - jentz-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 7575:8080
    networks:
      - jentz-network
volumes:
  postgres:

networks:
  jentz-network:
