# docker-compose.yml
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=RecipePassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5444:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 7575:8080
  api:
    build: .
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://recipe:RecipePassword@postgres:5432/recipe
volumes:
  postgres:
